/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminManagersRouteImport } from './routes/admin.managers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerAnnouncementsRouteImport } from './routes/manager.announcements'
import { Route as ManagerBuildingRouteImport } from './routes/manager.building'
import { Route as ManagerChargesRouteImport } from './routes/manager.charges'
import { Route as ManagerExpensesRouteImport } from './routes/manager.expenses'
import { Route as ManagerNotificationsRouteImport } from './routes/manager.notifications'
import { Route as ManagerPaymentsRouteImport } from './routes/manager.payments'
import { Route as ManagerPollsRouteImport } from './routes/manager.polls'
import { Route as ManagerProvidersRouteImport } from './routes/manager.providers'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerRequestsRouteImport } from './routes/manager.requests'
import { Route as ManagerResidentsRouteImport } from './routes/manager.residents'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as ManagerUnitsRouteImport } from './routes/manager.units'
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as ResidentChargesRouteImport } from './routes/resident.charges'
import { Route as ResidentPaymentsRouteImport } from './routes/resident.payments'
import { Route as ResidentRequestsRouteImport } from './routes/resident.requests'
import { Route as ResidentUnitRouteImport } from './routes/resident.unit'
import { Route as AdminBuildingsIndexRouteImport } from './routes/admin.buildings.index'
import { Route as AdminBuildingsIdRouteImport } from './routes/admin.buildings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagersRoute = AdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnnouncementsRoute = ManagerAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBuildingRoute = ManagerBuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerChargesRoute = ManagerChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerExpensesRoute = ManagerExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerNotificationsRoute = ManagerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPaymentsRoute = ManagerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPollsRoute = ManagerPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProvidersRoute = ManagerProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerRequestsRoute = ManagerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerResidentsRoute = ManagerResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerUnitsRoute = ManagerUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => ManagerRoute,
} as any)
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentChargesRoute = ResidentChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentPaymentsRoute = ResidentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentRequestsRoute = ResidentRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentUnitRoute = ResidentUnitRouteImport.update({
  id: '/unit',
  path: '/unit',
  getParentRoute: () => ResidentRoute,
} as any)
const AdminBuildingsIndexRoute = AdminBuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildingsIdRoute = AdminBuildingsIdRouteImport.update({
  id: '/buildings/$id',
  path: '/buildings/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/provider': typeof ProviderRoute
  '/resident': typeof ResidentRouteWithChildren
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/building': typeof ManagerBuildingRoute
  '/manager/charges': typeof ManagerChargesRoute
  '/manager/expenses': typeof ManagerExpensesRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/polls': typeof ManagerPollsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/requests': typeof ManagerRequestsRoute
  '/manager/residents': typeof ManagerResidentsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/units': typeof ManagerUnitsRoute
  '/resident/charges': typeof ResidentChargesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/requests': typeof ResidentRequestsRoute
  '/resident/unit': typeof ResidentUnitRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/admin/buildings/$id': typeof AdminBuildingsIdRoute
  '/admin/buildings/': typeof AdminBuildingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/provider': typeof ProviderRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/building': typeof ManagerBuildingRoute
  '/manager/charges': typeof ManagerChargesRoute
  '/manager/expenses': typeof ManagerExpensesRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/polls': typeof ManagerPollsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/requests': typeof ManagerRequestsRoute
  '/manager/residents': typeof ManagerResidentsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/units': typeof ManagerUnitsRoute
  '/resident/charges': typeof ResidentChargesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/requests': typeof ResidentRequestsRoute
  '/resident/unit': typeof ResidentUnitRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/resident': typeof ResidentIndexRoute
  '/admin/buildings/$id': typeof AdminBuildingsIdRoute
  '/admin/buildings': typeof AdminBuildingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/provider': typeof ProviderRoute
  '/resident': typeof ResidentRouteWithChildren
  '/admin/managers': typeof AdminManagersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/announcements': typeof ManagerAnnouncementsRoute
  '/manager/building': typeof ManagerBuildingRoute
  '/manager/charges': typeof ManagerChargesRoute
  '/manager/expenses': typeof ManagerExpensesRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/payments': typeof ManagerPaymentsRoute
  '/manager/polls': typeof ManagerPollsRoute
  '/manager/providers': typeof ManagerProvidersRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/requests': typeof ManagerRequestsRoute
  '/manager/residents': typeof ManagerResidentsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/units': typeof ManagerUnitsRoute
  '/resident/charges': typeof ResidentChargesRoute
  '/resident/payments': typeof ResidentPaymentsRoute
  '/resident/requests': typeof ResidentRequestsRoute
  '/resident/unit': typeof ResidentUnitRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/resident/': typeof ResidentIndexRoute
  '/admin/buildings/$id': typeof AdminBuildingsIdRoute
  '/admin/buildings/': typeof AdminBuildingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/provider'
    | '/resident'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/announcements'
    | '/manager/building'
    | '/manager/charges'
    | '/manager/expenses'
    | '/manager/notifications'
    | '/manager/payments'
    | '/manager/polls'
    | '/manager/providers'
    | '/manager/reports'
    | '/manager/requests'
    | '/manager/residents'
    | '/manager/settings'
    | '/manager/units'
    | '/resident/charges'
    | '/resident/payments'
    | '/resident/requests'
    | '/resident/unit'
    | '/admin/'
    | '/manager/'
    | '/resident/'
    | '/admin/buildings/$id'
    | '/admin/buildings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/provider'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/announcements'
    | '/manager/building'
    | '/manager/charges'
    | '/manager/expenses'
    | '/manager/notifications'
    | '/manager/payments'
    | '/manager/polls'
    | '/manager/providers'
    | '/manager/reports'
    | '/manager/requests'
    | '/manager/residents'
    | '/manager/settings'
    | '/manager/units'
    | '/resident/charges'
    | '/resident/payments'
    | '/resident/requests'
    | '/resident/unit'
    | '/admin'
    | '/manager'
    | '/resident'
    | '/admin/buildings/$id'
    | '/admin/buildings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/manager'
    | '/provider'
    | '/resident'
    | '/admin/managers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/manager/announcements'
    | '/manager/building'
    | '/manager/charges'
    | '/manager/expenses'
    | '/manager/notifications'
    | '/manager/payments'
    | '/manager/polls'
    | '/manager/providers'
    | '/manager/reports'
    | '/manager/requests'
    | '/manager/residents'
    | '/manager/settings'
    | '/manager/units'
    | '/resident/charges'
    | '/resident/payments'
    | '/resident/requests'
    | '/resident/unit'
    | '/admin/'
    | '/manager/'
    | '/resident/'
    | '/admin/buildings/$id'
    | '/admin/buildings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ProviderRoute: typeof ProviderRoute
  ResidentRoute: typeof ResidentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/managers': {
      id: '/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AdminManagersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/announcements': {
      id: '/manager/announcements'
      path: '/announcements'
      fullPath: '/manager/announcements'
      preLoaderRoute: typeof ManagerAnnouncementsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/building': {
      id: '/manager/building'
      path: '/building'
      fullPath: '/manager/building'
      preLoaderRoute: typeof ManagerBuildingRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/charges': {
      id: '/manager/charges'
      path: '/charges'
      fullPath: '/manager/charges'
      preLoaderRoute: typeof ManagerChargesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/expenses': {
      id: '/manager/expenses'
      path: '/expenses'
      fullPath: '/manager/expenses'
      preLoaderRoute: typeof ManagerExpensesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/notifications': {
      id: '/manager/notifications'
      path: '/notifications'
      fullPath: '/manager/notifications'
      preLoaderRoute: typeof ManagerNotificationsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/payments': {
      id: '/manager/payments'
      path: '/payments'
      fullPath: '/manager/payments'
      preLoaderRoute: typeof ManagerPaymentsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/polls': {
      id: '/manager/polls'
      path: '/polls'
      fullPath: '/manager/polls'
      preLoaderRoute: typeof ManagerPollsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/providers': {
      id: '/manager/providers'
      path: '/providers'
      fullPath: '/manager/providers'
      preLoaderRoute: typeof ManagerProvidersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/requests': {
      id: '/manager/requests'
      path: '/requests'
      fullPath: '/manager/requests'
      preLoaderRoute: typeof ManagerRequestsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/residents': {
      id: '/manager/residents'
      path: '/residents'
      fullPath: '/manager/residents'
      preLoaderRoute: typeof ManagerResidentsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/units': {
      id: '/manager/units'
      path: '/units'
      fullPath: '/manager/units'
      preLoaderRoute: typeof ManagerUnitsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/resident/': {
      id: '/resident/'
      path: '/'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/charges': {
      id: '/resident/charges'
      path: '/charges'
      fullPath: '/resident/charges'
      preLoaderRoute: typeof ResidentChargesRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/payments': {
      id: '/resident/payments'
      path: '/payments'
      fullPath: '/resident/payments'
      preLoaderRoute: typeof ResidentPaymentsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/requests': {
      id: '/resident/requests'
      path: '/requests'
      fullPath: '/resident/requests'
      preLoaderRoute: typeof ResidentRequestsRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/unit': {
      id: '/resident/unit'
      path: '/unit'
      fullPath: '/resident/unit'
      preLoaderRoute: typeof ResidentUnitRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/admin/buildings/': {
      id: '/admin/buildings/'
      path: '/buildings'
      fullPath: '/admin/buildings/'
      preLoaderRoute: typeof AdminBuildingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings/$id': {
      id: '/admin/buildings/$id'
      path: '/buildings/$id'
      fullPath: '/admin/buildings/$id'
      preLoaderRoute: typeof AdminBuildingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminManagersRoute: typeof AdminManagersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBuildingsIdRoute: typeof AdminBuildingsIdRoute
  AdminBuildingsIndexRoute: typeof AdminBuildingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminManagersRoute: AdminManagersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBuildingsIdRoute: AdminBuildingsIdRoute,
  AdminBuildingsIndexRoute: AdminBuildingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerAnnouncementsRoute: typeof ManagerAnnouncementsRoute
  ManagerBuildingRoute: typeof ManagerBuildingRoute
  ManagerChargesRoute: typeof ManagerChargesRoute
  ManagerExpensesRoute: typeof ManagerExpensesRoute
  ManagerNotificationsRoute: typeof ManagerNotificationsRoute
  ManagerPaymentsRoute: typeof ManagerPaymentsRoute
  ManagerPollsRoute: typeof ManagerPollsRoute
  ManagerProvidersRoute: typeof ManagerProvidersRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerRequestsRoute: typeof ManagerRequestsRoute
  ManagerResidentsRoute: typeof ManagerResidentsRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerUnitsRoute: typeof ManagerUnitsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAnnouncementsRoute: ManagerAnnouncementsRoute,
  ManagerBuildingRoute: ManagerBuildingRoute,
  ManagerChargesRoute: ManagerChargesRoute,
  ManagerExpensesRoute: ManagerExpensesRoute,
  ManagerNotificationsRoute: ManagerNotificationsRoute,
  ManagerPaymentsRoute: ManagerPaymentsRoute,
  ManagerPollsRoute: ManagerPollsRoute,
  ManagerProvidersRoute: ManagerProvidersRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerRequestsRoute: ManagerRequestsRoute,
  ManagerResidentsRoute: ManagerResidentsRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerUnitsRoute: ManagerUnitsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface ResidentRouteChildren {
  ResidentChargesRoute: typeof ResidentChargesRoute
  ResidentPaymentsRoute: typeof ResidentPaymentsRoute
  ResidentRequestsRoute: typeof ResidentRequestsRoute
  ResidentUnitRoute: typeof ResidentUnitRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentChargesRoute: ResidentChargesRoute,
  ResidentPaymentsRoute: ResidentPaymentsRoute,
  ResidentRequestsRoute: ResidentRequestsRoute,
  ResidentUnitRoute: ResidentUnitRoute,
  ResidentIndexRoute: ResidentIndexRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ProviderRoute: ProviderRoute,
  ResidentRoute: ResidentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
